run:
    go run main.go serve

run_test:
    go run main.go serve --dir="./test_pb_data"

tests_snapshot:
    go run main.go migrate collections --dir="./test_pb_data"

snapshot:
    go run main.go migrate collections

test:
    go test ./...
